"""G-code generation for Marlin-based CNC pancake printer."""

import math
from dataclasses import dataclass, field

import numpy as np


@dataclass
class GCodeConfig:
    """Configuration for G-code generation."""
    bed_width: float = 200.0       # mm
    bed_height: float = 200.0      # mm
    feed_travel: int = 3000        # mm/min for G0 rapid moves
    feed_dispense: int = 600       # mm/min for G1 dispense moves
    extrusion_rate: float = 0.05   # E value per mm of travel
    z_height: float = 1.0          # nozzle height above griddle
    tool_codes: list = field(default_factory=lambda: ["T0", "T1", "T2"])


def pixels_to_mm(points, image_shape, config):
    """Convert pixel coordinates to mm coordinates on the print bed.

    Preserves aspect ratio, centers the image on the bed, and flips Y axis
    (image Y goes down, CNC Y goes up).

    Args:
        points: Nx2 array of pixel coordinates (x, y)
        image_shape: (height, width) of the source image
        config: GCodeConfig with bed dimensions

    Returns:
        Nx2 array of mm coordinates
    """
    img_h, img_w = image_shape[:2]

    # Scale factor to fit image on bed while preserving aspect ratio
    scale_x = config.bed_width / img_w
    scale_y = config.bed_height / img_h
    scale = min(scale_x, scale_y)

    # Centered offset
    offset_x = (config.bed_width - img_w * scale) / 2.0
    offset_y = (config.bed_height - img_h * scale) / 2.0

    mm_points = np.zeros_like(points, dtype=float)
    mm_points[:, 0] = points[:, 0] * scale + offset_x       # X
    mm_points[:, 1] = (img_h - points[:, 1]) * scale + offset_y  # Y flipped

    return mm_points


def _distance(p1, p2):
    """Euclidean distance between two 2D points."""
    return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)


def generate_gcode(layers, image_shape, config=None):
    """Generate complete Marlin G-code from print layers.

    Args:
        layers: List of layers. Each layer is a list of contour arrays.
                Layer 0 is darkest (dispensed first).
        image_shape: (height, width) of the source image for coordinate scaling
        config: GCodeConfig (uses defaults if None)

    Returns:
        Complete G-code as a string
    """
    if config is None:
        config = GCodeConfig()

    lines = []

    # Header
    lines.append("; Pancake Printer G-code")
    lines.append("; Generated by PancakePrint")
    lines.append(f"; Layers: {len(layers)}")
    lines.append("")
    lines.append("G21 ; Metric units (mm)")
    lines.append("G90 ; Absolute positioning")
    lines.append("G28 ; Home all axes")
    lines.append(f"G0 Z{config.z_height:.1f} F{config.feed_travel} ; Set nozzle height")
    lines.append("")

    total_extrusion = 0.0

    for layer_idx, contours in enumerate(layers):
        if not contours:
            continue

        # Tool change for this layer's batter dispenser
        tool = config.tool_codes[layer_idx] if layer_idx < len(config.tool_codes) else config.tool_codes[-1]
        lines.append(f"; --- Layer {layer_idx} ({tool}) ---")
        lines.append(f"{tool} ; Select batter dispenser")
        lines.append("G92 E0 ; Reset extruder position")
        total_extrusion = 0.0
        lines.append("")

        for contour in contours:
            # Reshape contour points: Nx1x2 -> Nx2
            pts = contour.reshape(-1, 2)
            if len(pts) < 2:
                continue

            # Convert to mm coordinates
            mm_pts = pixels_to_mm(pts, image_shape, config)

            # Travel to start of contour (no extrusion)
            start = mm_pts[0]
            lines.append(f"G0 X{start[0]:.2f} Y{start[1]:.2f} F{config.feed_travel}")

            # Dispense along the contour
            for i in range(1, len(mm_pts)):
                dist = _distance(mm_pts[i - 1], mm_pts[i])
                total_extrusion += dist * config.extrusion_rate
                lines.append(
                    f"G1 X{mm_pts[i][0]:.2f} Y{mm_pts[i][1]:.2f} "
                    f"E{total_extrusion:.4f} F{config.feed_dispense}"
                )

            # Close the contour if it has enough points
            if len(mm_pts) >= 3:
                dist = _distance(mm_pts[-1], mm_pts[0])
                total_extrusion += dist * config.extrusion_rate
                lines.append(
                    f"G1 X{mm_pts[0][0]:.2f} Y{mm_pts[0][1]:.2f} "
                    f"E{total_extrusion:.4f} F{config.feed_dispense}"
                )

            lines.append("")

    # Footer
    lines.append("; --- End ---")
    lines.append("G0 Z10.0 F{} ; Raise nozzle".format(config.feed_travel))
    lines.append("G28 X Y ; Home X and Y")
    lines.append("M84 ; Disable motors")
    lines.append("")

    return "\n".join(lines)
